### PR TITLE
add buildfoldername kwarg to servedocs

### PR DESCRIPTION
**Pull request by cserteGT3**
Similiarly to  #100  one can change name of the build folder, at least in Documenter.jl. This PR enables this functionality for LiveServer.jl as well.

### CODE REVIEW

**Comment by cserteGT3** [comment]
To be honest, I don't see how this could be tested.

**Comment by cserteGT3** [comment]
Okay, I had a couple of issues, but they were related to my script (and not to this package). As far as I understand `servedocs` is not tested, so I don't know if these changes could be merged in without adding the tests.

As mentioned above, I have no idea how to test this feature/kwarg, but if you give me some guidance, I'll happily implement it.

**Comment by cserteGT3** [comment]
I've also done a rebase.

**Comment by tlienart** [comment]
Thanks a lot! Yes servedocs is not directly tested; I'll have a look at what you did once I have a minute :) thanks again for contributing!

**Comment by cserteGT3** [comment]
Can I have a bump please? 😄

**Comment by tlienart** [comment]
oh! sorry!

**Comment by tlienart** [comment]
I'll double check tests pass then will release

**Comment by tlienart** [comment]
uh but the tests don't pass :'(

**Comment by tlienart** [comment]
ok fixed & released!

**Comment by cserteGT3** [comment]
Thank you for taking care of it!

**Pull request merged**
